sudo: false

language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/alecthomas/gometalinter

before_script:
  - gometalinter

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
